config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root 'properties#index'

  resources :properties

  get 'rentals', to: 'properties#rentals'
  get 'sales', to: 'properties#sales'
  get 'admin', to: 'properties#admin'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/property.rb
class Property < ActiveRecord::Base
  belongs_to :user
  geocoded_by :address
  after_validation :geocode

  validates :active, presence: true, length: { minimum: 2, maximum: 3 }
  validates :status, presence: true, length: { minimum: 3, maximum: 15 }
  validates :neighborhood, presence: true, length: { minimum: 2, maximum: 20 }
  validates :price, presence: true, length: { minimum: 3, maximum: 10 }
  validates :address, presence: true, length: { minimum: 3, maximum: 100 }
  validates :proximity, presence: true, length: { minimum: 3, maximum: 100 }
  validates :description, presence: true, length: { minimum: 3 }
  validates :doorman, presence: true, length: { minimum: 2, maximum: 3 }
  validates :outdoor, presence: true, length: { minimum: 2, maximum: 3 }
  validates :property_type, presence: true, length: { minimum: 3, maximum: 15 }
  validates :bed, presence: true, length: { minimum: 1, maximum: 2 }
  validates :bath, presence: true, length: { minimum: 1, maximum: 2 }
  validates :images, presence: true, length: { minimum: 1, maximum: 2 }
  validates :images_folder, presence: true, length: { minimum: 5, maximum: 20 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :properties
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def render_not_found(status = :not_found)
    render text: status.to_s.titleize.to_s, status: status
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :authenticate_user!, only: [:admin, :new, :create, :edit, :update, :destroy]

  def index
    @properties = Property.order(price: :desc)
  end

  def sales
    @sales = Property.order(price: :desc).where(active: 'Yes', status: 'For Sale')
    @contract = Property.order(price: :desc).where(status: 'In Contract')
    @sold = Property.order(price: :desc).where(active: 'Yes', status: 'Sold')
  end

  def rentals
    @rentals = Property.order(price: :desc).where(active: 'Yes', status: 'For Rent')
  end

  def admin
    @sales = Property.order(price: :desc).where(status: 'For Sale')
    @contract = Property.order(price: :desc).where(status: 'In Contract')
    @sold = Property.order(price: :desc).where(status: 'Sold')
    @rentals = Property.order(price: :desc).where(status: 'For Rent')
  end

  def new
    @property = Property.new
  end

  def create
    @property = Property.create(property_params)
    if @property.valid?
      redirect_to admin_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @property = current_property
    return render_not_found if @property.blank?
  end

  def edit
    @property = current_property
    return render_not_found if @property.blank?
  end

  def update
    @property = current_property
    return render_not_found if @property.blank?

    @property.update_attributes(property_params)
    if @property.valid?
      redirect_to admin_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @property = current_property
    return render_not_found if @property.blank?
    @property.destroy
    redirect_to admin_path
  end

  private

  def current_property
    @current_property ||= Property.find_by(id: params[:id])
  end

  def property_params
    params.require(:property).permit(:active, :status, :neighborhood, :price, :address, :proximity, :description, :doorman, :outdoor, :notes, :property_type, :bed, :bath, :maintenance, :images, :images_folder)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_action :one_user_registered?, only: [:new, :create]

  protected

  def one_user_registered?
    if (User.count == 1) & user_signed_in?
      redirect_to admin_path
    elsif User.count == 1
      redirect_to new_user_session_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Frederick Palmer Realty</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="content_holder">
<div id="center">
<span class="logo_holder pull-left"><%= link_to 'Frederick Palmer Realty', root_path, class: 'logo' %></span>
<span class="pull-right phone">718-783-1010</span>
<div class="clear_both"></div>
<%= yield %>
</div>
</div>
</body>
</html>

app/views/properties/admin.html.erb
<hr>
<% if notice.present? %>
<p class="alert alert-info"><%= notice %></p>
<% end %>
<% if alert.present? %>
<p class="alert alert-danger"><%= alert %></p>
<% end %>
<h3>Admin</h3>
<div class="list_holder">
<%= link_to "Add New Property", new_property_path %>
<%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'pull-right' %>
</div>
<hr>
<h4>For Sale: <%= @sales.count %></h4>
<div class="list_holder">
<% @sales.each do |property| %>
<div><%= link_to "Edit", edit_property_path(property.id) %> - <b>Active:</b> <%= property.active %> - <%= property.status %> - $<%= number_with_delimiter(property.price, :delimiter => ',') %> - <%= property.address %> - <%= property.neighborhood %></div>
<% end %>
</div>
<hr>
<h4>In Contract: <%= @contract.count %></h4>
<div class="list_holder">
<% @contract.each do |property| %>
<div><%= link_to "Edit", edit_property_path(property.id) %> - <b>Active:</b> <%= property.active %> - <%= property.status %> - $<%= number_with_delimiter(property.price, :delimiter => ',') %> - <%= property.address %> - <%= property.neighborhood %></div>
<% end %>
</div>
<hr>
<h4>Sold: <%= @sold.count %></h4>
<div class="list_holder">
<% @sold.each do |property| %>
<div><%= link_to "Edit", edit_property_path(property.id) %> - <b>Active:</b> <%= property.active %> - <%= property.status %> - $<%= number_with_delimiter(property.price, :delimiter => ',') %> - <%= property.address %> - <%= property.neighborhood %></div>
<% end %>
</div>
<hr>
<h4>For Rent: <%= @rentals.count %></h4>
<div class="list_holder">
<% @rentals.each do |property| %>
<div><%= link_to "Edit", edit_property_path(property.id) %> - <b>Active:</b> <%= property.active %> - <%= property.status %> - $<%= number_with_delimiter(property.price, :delimiter => ',') %> - <%= property.address %> - <%= property.neighborhood %></div>
<% end %>
</div>
<br />

app/views/properties/edit.html.erb
<hr>
<h3>Update property</h3>
<div class="list_holder">
<%= simple_form_for(@property, html: { class: 'form-horizontal' }) do |f| %>
<div class="form_left">
  <%= f.input :active, collection: [:Yes, :No], as: :radio_buttons, :item_wrapper_class => 'inline' %>
  <%= f.input :status, collection: ['For Sale', 'In Contract', 'Sold', 'For Rent'], prompt: '' %>
  <%= f.input :neighborhood %>
  <%= f.input :address %>
  <%= f.input :proximity %>
</div>
<div class="form_center">
  <%= f.input :price %>
  <%= f.input :maintenance %>
  <%= f.input :property_type, collection: ['Co-Op', 'Condo', 'House', 'Commercial'], prompt: '' %>
  <%= f.input :bed, collection: 0..10, prompt: '' %>
  <%= f.input :bath, collection: 0..10, prompt: '' %>
</div>
<div class="form_right">
  <%= f.input :doorman, collection: [:Yes, :No], as: :radio_buttons, :item_wrapper_class => 'inline' %>
  <%= f.input :outdoor, collection: [:Yes, :No], as: :radio_buttons, :item_wrapper_class => 'inline' %>
  <%= f.input :notes %>
  <%= f.input :images, collection: 0..20, prompt: '' %>
  <%= f.input :images_folder %>
</div>
<div class="form_bottom">
<%= f.input :description %>
</div>
  <%= f.button :submit, class: 'btn btn-success' %>
    <%= link_to 'Cancel', admin_path, class: 'btn btn-warning' %>
  <%= link_to 'Delete Property', property_path(@property), method: :delete, data: { confirm:'Are you sure you want to delete this property?' }, class: 'btn btn-danger pull-right' %> 
<% end %>
</div>
<br />

app/views/properties/index.html.erb
<div id="bridge">
<div id="menu">
<div id="menu_items"><%= link_to 'Sales', sales_path %>&nbsp;&nbsp;&nbsp;&mdash;&nbsp;&nbsp;&nbsp;<%= link_to 'Rentals', rentals_path %></div>
</div>
</div>
<div id="disclaimer">Although all information furnished regarding property for sale or rental is from sources deemed reliable, such information has not been verified and no express representation is made, nor any to be implied, as to the accuracy thereof, and is submitted subject to errors, omissions, change of price or other conditions, prior sale, lease, or withdrawal without notice.</div> 

app/views/properties/new.html.erb
<hr>
<h3>Add New Property</h3>
<div class="list_holder">
<%= simple_form_for(@property, html: { class: 'form-horizontal' }) do |f| %>
<div class="form_left">
  <%= f.input :active, collection: [:Yes, :No], as: :radio_buttons, :item_wrapper_class => 'inline' %>
  <%= f.input :status, collection: ['For Sale', 'In Contract', 'Sold', 'For Rent'], prompt: "Status?" %>
  <%= f.input :neighborhood %>
  <%= f.input :address %>
  <%= f.input :proximity %>
</div>
<div class="form_center">
  <%= f.input :price %>
  <%= f.input :maintenance %>
  <%= f.input :property_type, collection: ['Co-Op', 'Condo', 'House', 'Commercial'], prompt: "Type?" %>
  <%= f.input :bed, collection: 0..10, prompt: "How many?" %>
  <%= f.input :bath, collection: 0..10, prompt: "How many?" %>
</div>
<div class="form_right">
  <%= f.input :doorman, collection: [:Yes, :No], as: :radio_buttons, :item_wrapper_class => 'inline' %>
  <%= f.input :outdoor, collection: [:Yes, :No], as: :radio_buttons, :item_wrapper_class => 'inline' %>
  <%= f.input :notes %>
  <%= f.input :images, collection: 0..20, prompt: "How many?" %>
  <%= f.input :images_folder %>
</div>
<div class="form_bottom">
<%= f.input :description %>
</div>
  <%= f.button :submit, class: 'btn btn-success' %>
  <%= link_to 'Cancel', admin_path, class: 'btn btn-warning' %>
<% end %>
</div>
<br />

app/views/properties/rentals.html.erb
<hr>
<h3>Rentals</h3>
<div class="list_holder">
<% @rentals.each do |property| %>
<div class="property_holder">
<%= link_to property_path(property.id) do %>
<%= image_tag property.images_folder + '/1.jpg'%>
<% end %>
<div class="address"><div class="location"><%= link_to property.address.split(',').first, property_path(property.id) %></div><div class="neighborhood"><%= property.neighborhood %></div><div class="proximity"><%= property.proximity %></div><div class="status"><%= property.status %></div></div><div class="type">Type<br /><br /><%= property.property_type %></div><div class="bedrooms">Beds<br /><br /><%= property.bed %></div><div class="bathrooms">Baths<br /><br /><%= property.bath %></div><div class="price">Price<br /><br />$<%= number_with_delimiter(property.price, :delimiter => ',') %></div>
<div class="clear_left"></div>
</div>
<% end %>
</div>
<script>
$( ".property_holder:last" ).css({ backgroundImage: "none", paddingBottom: "12px" });
</script>

app/views/properties/sales.html.erb
<hr>
<h3>Sales</h3>
<div class="list_holder">
<% @sales.each do |property| %>
<div class="property_holder">
<%= link_to property_path(property.id) do %>
<%= image_tag property.images_folder + '/1.jpg'%>
<% end %>
<div class="address"><div class="location"><%= link_to property.address.split(',').first, property_path(property.id) %></div><div class="neighborhood"><%= property.neighborhood %></div><div class="proximity"><%= property.proximity %></div><div class="status"><%= property.status %></div></div><div class="type">Type<br /><br /><%= property.property_type %></div><div class="bedrooms">Beds<br /><br /><%= property.bed %></div><div class="bathrooms">Baths<br /><br /><%= property.bath %></div><div class="price">Price<br /><br />$<%= number_with_delimiter(property.price, :delimiter => ',') %></div>
<div class="clear_left"></div>
</div>
<% end %>
</div>
<div class="list_holder">
<% @contract.each do |property| %>
<div class="property_holder">
<%= link_to property_path(property.id) do %>
<%= image_tag property.images_folder + '/1.jpg'%>
<% end %>
<div class="address"><div class="location"><%= link_to property.address.split(',').first, property_path(property.id) %></div><div class="neighborhood"><%= property.neighborhood %></div><div class="proximity"><%= property.proximity %></div><div class="status"><%= property.status %></div></div><div class="type">Type<br /><br /><%= property.property_type %></div><div class="bedrooms">Beds<br /><br /><%= property.bed %></div><div class="bathrooms">Baths<br /><br /><%= property.bath %></div><div class="price">Price<br /><br />$<%= number_with_delimiter(property.price, :delimiter => ',') %></div>
<div class="clear_left"></div>
</div>
<% end %>
</div>
<div class="list_holder">
<% @sold.each do |property| %>
<div class="property_holder">
<%= link_to property_path(property.id) do %>
<%= image_tag property.images_folder + '/1.jpg'%>
<% end %>
<div class="address"><div class="location"><%= link_to property.address.split(',').first, property_path(property.id) %></div><div class="neighborhood"><%= property.neighborhood %></div><div class="proximity"><%= property.proximity %></div><div class="status"><%= property.status %></div></div><div class="type">Type<br /><br /><%= property.property_type %></div><div class="bedrooms">Beds<br /><br /><%= property.bed %></div><div class="bathrooms">Baths<br /><br /><%= property.bath %></div><div class="price">Price<br /><br />$<%= number_with_delimiter(property.price, :delimiter => ',') %></div>
<div class="clear_left"></div>
</div>
<% end %>
</div>
<script>
$( ".property_holder:last" ).css({ backgroundImage: "none", paddingBottom: "12px" });
</script>

app/views/properties/show.html.erb
<hr>
<div class="list_holder">
<div id="showcontent">
<div class="show_location"><%= @property.address.split(',').first %></div>
<div class="show_neighborhood"><%= @property.neighborhood %></div>
<div class="show_proximity"><%= @property.proximity %></div>
<div class="show_price">$<%= number_with_delimiter(@property.price, :delimiter => ',') %></div>
<table cellpadding="0" cellpadding="0">
<% if @property.notes.present? %>
<tr><td align="left" colspan="2"><span class="show_notes"><%= @property.notes %></span></td></tr>
<% end %>
<% if @property.maintenance.present? %>
<tr><td>Maintenance</td><td align="right">$<%= @property.maintenance %></td></tr>
<% end %>
<tr><td>Type</td><td align="right"><%= @property.property_type %></td></tr>
<tr><td>Beds</td><td align="right"><%= @property.bed %></td></tr>
<tr><td>Baths</td><td align="right"><%= @property.bath %></td></tr>
<tr><td>Doorman</td><td align="right"><%= @property.doorman %></td></tr>
<tr><td>Outdoor Space</td><td align="right"><%= @property.outdoor %></td></tr>
<tr><td colspan="2">&nbsp;</td></tr>
<% if (@property.status != 'For Rent') %>
<tr><td colspan="2" align="center"><%= link_to 'Mortage Calculator', '#', data: {toggle: 'modal', target: '#myModal'} %></td></tr>
<% end %>
</table>
</div>
  <div id="photos">
  <div class="w3-content w3-display-container">
  <% n = 1 %>
  <% @property.images.times do %>
  <%= image_tag @property.images_folder + '/' + n.to_s + '.jpg', class: 'mySlides' %>
  <% n += 1 %>
  <% end %>
  <a class="w3-btn-floating w3-display-left" onclick="plusDivs(-1)">&#10094;</a>
  <a class="w3-btn-floating w3-display-right" onclick="plusDivs(+1)">&#10095;</a>
  </div>
  <div class="w3-content w3-display-container w3-display-center">
  <% n = 1 %>
  <% @property.images.times do %>
  <span class='w3-badge demo w3-border w3-transparent w3-hover-black' onclick='currentDiv(<%= n.to_s %>)'></span>
  <% n += 1 %>
  <% end %>
  </div>
  <script>
  showDivs(slideIndex);
  </script>
</div>
<div class="clear_left"></div>
<div class="show_description"><%= @property.description.html_safe %></div>
<% if @property.latitude.present? && @property.longitude.present? %>
<div id="map"></div>
    <script>
      function initMap() {
        var myLatLng = {lat: <%= @property.latitude %>, lng: <%= @property.longitude %>};
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 14,
          center: myLatLng
        });
        var marker = new google.maps.Marker({
          position: myLatLng,
          map: map
        });
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAq1nE3WDOJD4EXPCMb0JzEpyS97KlZu20&callback=initMap">
    </script>
    <% end %>
    <div class="clear_left"></div>
      <!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h3 class="modal-title" id="myModalLabel">Mortage Calculator</h3>
        </div>
        <div class="modal-body">
          <div id="mort_calc">
<form name=temps>
<table cellspacing="0" cellpadding="0" width="100%">
<tr><td>Years:</td><td align="right"><input onChange=dosum() size=6 value=30 name=YR></td></tr>
<tr><td>Interest:</td><td align="right"><input onChange=dosum() size=6 value=3.5 name=IR></td></tr>
<tr><td>Loan Amount:</td><td align="right"><input onchange=dosum() size=6 name=LA></td></tr>
<tr><td>Annual Tax:</td><td align="right"><input onchange=dosum() size=6 name=AT></td></tr>
<tr><td>Annual Insurance:</td><td align="right"><input onchange=dosum() size=6 name=AI></td></tr>
<tr><td align="center" colspan="2"><input onClick=dosum() type=button value="Calculate Payment" class="btn calculate"></td></tr>
<tr><td>Monthly Principal + Interest:</td><td align="right"><input size=10 name=PI></td></tr>
<tr><td>Monthly Tax:</td><td align="right"><input size=10 name=MT></td></tr>
<tr><td>Monthly Insurance:</td><td align="right"><input size=10 name=MI></td></tr>
<tr><td>Total Payment:</td><td align="right"><input size=10 name=MP></td></tr>
</table>
</form>
</div>
        </div>
      </div>
    </div>
</div><!--Modal end-->